version: '3.1'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    networks:
      - backend
      - mysql_mysqlnetwork
    environment:
      - CONTAINER_TIMEZONE=Asia/Bangkok
      - VIRTUAL_HOST=local-vhost.dev

  networks:
    backend:
      driver: bridge
    mysql_mysqlnetwork:
      external: true
